format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM-IoT_WG_Development_Board, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '370', y: '294', id: BSP_SAM-IoT_WG_Development_Board}
