format_version: v1.0
type: UniqueComponent
attributes: {id: HarmonyCore}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: APP0_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app1.c}
  - type: File
    attributes: {id: APP0_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app1.h}
  - type: File
    attributes: {id: APP1_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app2.c}
  - type: File
    attributes: {id: APP1_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app2.h}
  - type: File
    attributes: {id: APP2_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app3.c}
  - type: File
    attributes: {id: APP2_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app3.h}
  - type: File
    attributes: {id: APP3_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app4.c}
  - type: File
    attributes: {id: APP3_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: app4.h}
  - type: KeyValueSet
    attributes: {id: COMMON_SYMBOL_CNTR}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: 'TRUE', value: '1', key: ENABLE_DRV_COMMON}
          - type: Pair
            attributes: {description: 'TRUE', value: '2', key: ENABLE_SYS_COMMON}
          - type: Pair
            attributes: {description: 'FALSE', value: '0', key: ENABLE_SYS_MEDIA}
          - type: Pair
            attributes: {description: 'FALSE', value: '0', key: ENABLE_SYS_PORTS}
          - type: Pair
            attributes: {description: 'FALSE', value: '0', key: ENABLE_SYS_DMA}
          - type: Pair
            attributes: {description: 'TRUE', value: '1', key: ENABLE_SYS_RESET}
  - type: Boolean
    attributes: {id: ENABLE_APP_FILE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_DRV_COMMON}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_OSAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_CACHE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'false'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_COMMON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_DMA}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_INT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_PORTS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SYS_RESET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: 'true'}
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: GEN_APP_RTOS_TASK_0_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '512'}
  - type: Boolean
    attributes: {id: GEN_APP_RTOS_TASK_0_USE_DELAY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Menu
    attributes: {id: GEN_APP_RTOS_TASK_CONF_MENU0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_RTOS_TASK_CONF_MENU1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_RTOS_TASK_CONF_MENU2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_RTOS_TASK_CONF_MENU3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_TASK_CONF_MENU0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_TASK_CONF_MENU1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_TASK_CONF_MENU2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: GEN_APP_TASK_CONF_MENU3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: GEN_APP_TASK_COUNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: String
    attributes: {id: GEN_APP_TASK_NAME_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: app1}
  - type: String
    attributes: {id: GEN_APP_TASK_NAME_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: app2}
  - type: String
    attributes: {id: GEN_APP_TASK_NAME_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: app3}
  - type: String
    attributes: {id: GEN_APP_TASK_NAME_3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: app4}
  - type: File
    attributes: {id: PORTS_DEF}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: PORTS_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: PORTS_MAPPING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: RESET_DEF}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: RESET_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: RESET_MAPPING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: SELECT_RTOS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: HarmonyCore, value: FreeRTOS}
- type: ElementPosition
  attributes: {x: '30', y: '100', id: HarmonyCore}
